<?php 
error_reporting(E_ALL & ~E_NOTICE);
@require_once("requires/session.php");

$objDb  		= new Database( );
if ($uname==null  ) {
header("Location: index.php?init=3");
}
else if ($process_flag==0 ) {
header("Location: index.php?init=3");
}
$msg	= "";
?>
<?php 
$q1="TRUNCATE `activity` ";
$q2="TRUNCATE `activity_log` ";
$q3="TRUNCATE `baseline` ";
$q4="TRUNCATE `baseline_mapping_boqs` ";
$q5="TRUNCATE `baseline_template` ";
$q6="TRUNCATE `base_data_cube` ";
$q7="TRUNCATE `boq` ";
$q8="TRUNCATE `boqdata` ";
$q9="TRUNCATE `ipc` ";
$q10="TRUNCATE `ipcv` ";
$q11="TRUNCATE `ipc_log` ";
$q12="TRUNCATE `kpidata` ";
$q13="TRUNCATE `kpidata_etl` ";
$q14="TRUNCATE `kpidata_result` ";
$q15="TRUNCATE `kpiscale` ";
$q16="TRUNCATE `kpi_activity` ";
$q17="TRUNCATE `kpi_base_level_report` ";
$q18="TRUNCATE `kpi_monthly_progress_report` ";
$q19="TRUNCATE `kpi_templates` ";
$q20="TRUNCATE `kpi_top_level_report` ";
$q21="TRUNCATE `kpi_total_baseline` ";
$q22="TRUNCATE `locations` ";
$q23="TRUNCATE `maindata` ";
$q24="TRUNCATE `maindata_log` ";
$q25="TRUNCATE `main_data_cube` ";
$q26="TRUNCATE `mildata` ";
$q27="TRUNCATE `pages_visit_log` ";
$q28="TRUNCATE `planned` ";
$q29="TRUNCATE `progress` ";
$q30="TRUNCATE `progressmonth` ";
$q31="TRUNCATE `progressmonth_log` ";
$q32="TRUNCATE `project` ";
$q33="TRUNCATE `project_currency` ";
$q34="TRUNCATE `project_days` ";
$q35="TRUNCATE `project_photos` ";
$q36="TRUNCATE `project_weekdays` ";
$q37="TRUNCATE `results` ";
$q38="TRUNCATE `s006-eva-budget` ";
$q39="TRUNCATE `s007-eva-earned` ";
$q40="TRUNCATE `s008-eva-actual` ";
$q41="TRUNCATE `s009-eva-results` ";
$q42="TRUNCATE `t0101designprogress` ";
$q43="TRUNCATE `t012issues` ";
$q44="TRUNCATE `t013nonconformitynotice` ";
$q45="TRUNCATE `t014majoritems` ";
$q46="TRUNCATE `t023project_progress_graph` ";
$q47="TRUNCATE `t027project_drawings` ";
$q48="TRUNCATE `t027project_photos` ";
$q49="TRUNCATE `t031project_albums` ";
$q50="TRUNCATE `t031project_drawingalbums` ";
$q51="TRUNCATE `t32project_videos` ";
$q52="TRUNCATE `template_progress` ";
$q53="TRUNCATE `users_log` ";
$q54="TRUNCATE `yearly_holidays` ";
mysql_query($q1);
mysql_query($q2);
mysql_query($q3);
mysql_query($q4);
mysql_query($q5);
mysql_query($q6);
mysql_query($q7);
mysql_query($q8);
mysql_query($q9);
mysql_query($q10);
mysql_query($q11);
mysql_query($q12);
mysql_query($q13);
mysql_query($q14);
mysql_query($q15);
mysql_query($q16);
mysql_query($q17);
mysql_query($q18);
mysql_query($q19);
mysql_query($q20);
mysql_query($q21);
mysql_query($q22);
mysql_query($q23);
mysql_query($q24);
mysql_query($q25);
mysql_query($q26);
mysql_query($q27);
mysql_query($q28);
mysql_query($q29);
mysql_query($q30);
mysql_query($q31);
mysql_query($q32);
mysql_query($q33);
mysql_query($q34);
mysql_query($q35);
mysql_query($q36);
mysql_query($q37);
mysql_query($q38);
mysql_query($q39);
mysql_query($q40);
mysql_query($q41);
mysql_query($q42);
mysql_query($q43);
mysql_query($q44);
mysql_query($q45);
mysql_query($q46);
mysql_query($q47);
mysql_query($q48);
mysql_query($q49);
mysql_query($q50);
mysql_query($q51);
mysql_query($q52);
mysql_query($q53);
mysql_query($q54);
echo "Data Clearing Process is complete";
 ?>
 <a class="button" href="javascript:void(null);" onclick="window.close();" ><strong>Close</strong></a>